[package]
name = "guild-mayhem"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alsa = "=0.5.0"
heron = { version = "0.12.1", features = ["3d"] }

[dependencies.bevy]
version = "0.5.0"
